apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - secret/

resources:
- resources/kuard.yaml

namespace: kuard-demo

patchesJson6902:
  - path: patches/set-cert-issuer.patch.yaml
    target:
      group: cert-manager.io
      kind: Certificate
      name: kuard-tls
      version: v1alpha3
