---
apiVersion: v1
kind: Service
metadata:
  name: contour-envoy
  namespace: projectcontour
spec:
  externalTrafficPolicy: Local
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: http
  - port: 443
    name: https
    protocol: TCP
    targetPort: https
  selector:
    app: contour-envoy
  type: LoadBalancer
