---
apiVersion: v1
kind: Service
metadata:
  name: contour
  namespace: projectcontour
spec:
  ports:
  - port: 8001
    name: xds
    protocol: TCP
    targetPort: 8001
  selector:
    app: contour
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: xds-lockdown
spec:
  podSelector:
    matchLabels:
      app: contour
  ingress:
  - ports:
    - port: xds
    from:
    - podSelector:
        matchLabels:
          app: contour-envoy
