apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- serviceaccount.yaml
- certificate.yaml
- role.yaml
- rolebinding.yaml

images:
- name: htpasswd
  newName: contour-authserver
  newTag: latest
